# Generated by Django 4.2.4 on 2023-08-19 09:19
import django.db.utils
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movie_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='new', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
